spring.application.name=suporteos
<<<<<<< HEAD
spring.profiles.active=test
=======
spring.profiles.active=test

#swagger log
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true
>>>>>>> 97f7a06 (adição do swagger)
