spring.application.name=suporteos
spring.profiles.active=test

jwt.secret=gUL9xEMTDsAGxtmVhsoAcd9YkY+S5+2kYPj99g6rjvYjkTL/TdQKbk5vpgVZnMP7piNk8zB9Yps7Zbl0aOyDwA==
jwt.expiration=180000

#swagger log
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true

